include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 80

analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**/**.g.dart"
    - "lib/**.g.dart"
    - "**/**.freezed.dart"
    - "lib/**.freezed.dart"
    - "lib/i18n/*"
    - "build/**"
    - "lib/generated/**"

  language:
    #strict-casts: true
    #strict-inference: true
    #strict-raw-types: true

  errors:
    todo: ignore
    always_use_package_imports: warning
    avoid_print: warning
    annotate_overrides: warning
    avoid_renaming_method_parameters: warning
    avoid_return_types_on_setters: warning
    avoid_returning_null_for_void: error
    avoid_unnecessary_containers: warning
    camel_case_types: error
    flutter_style_todos: warning
    invalid_annotation_target: ignore
    always_declare_return_types: warning
    unused_import: error
    require_trailing_commas: info
    sort_child_properties_last: warning
    no_leading_underscores_for_local_identifiers: info
    use_string_in_part_of_directives: ignore
    

   
linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    annotate_overrides: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    flutter_style_todos: true
    always_declare_return_types: true    
    require_trailing_commas: true
    sort_child_properties_last: true
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    depend_on_referenced_packages: false
    remove_deprecations_in_breaking_versions: true
    unnecessary_unawaited: true


