include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false
    ## temporal off
    flutter_style_todos: false
    discarded_futures: false
    unawaited_futures: false
    document_ignores: false
    unreachable_from_main: false
    cancel_subscriptions: false
